ALTER TABLE "Post" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1,
 ADD COLUMN "author" TEXT NOT NULL DEFAULT '', ADD COLUMN "coverUrl" TEXT NOT NULL DEFAULT '',
 ADD COLUMN "coverAlt" TEXT NOT NULL DEFAULT '', ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "seoTitle" TEXT NOT NULL DEFAULT '', ADD COLUMN "seoDescription" TEXT NOT NULL DEFAULT '';
CREATE TABLE "PostRevision" ("id" UUID NOT NULL, "postId" UUID NOT NULL, "version" INTEGER NOT NULL, "snapshot" JSONB NOT NULL, "actorId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PostRevision_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PostRevision_postId_version_key" ON "PostRevision"("postId","version");
ALTER TABLE "PostRevision" ADD CONSTRAINT "PostRevision_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Enquiry" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "assigneeId" TEXT, ADD COLUMN "followUpAt" TIMESTAMP(3);
ALTER TABLE "PrivacyRequest" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "assigneeId" TEXT, ADD COLUMN "followUpAt" TIMESTAMP(3);
