/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsSlugRouteImport } from './routes/admin.posts.$slug'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminPostsSlugIndexRouteImport } from './routes/admin.posts.$slug.index'
import { Route as AdminPostsSlugEditRouteImport } from './routes/admin.posts.$slug.edit'
import { Route as AdminProductsSlugIndexRouteImport } from './routes/admin.products.$slug.index'
import { Route as AdminProductsSlugEditRouteImport } from './routes/admin.products.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogueRoute,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogueRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsSlugRoute = AdminPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminPostsSlugIndexRoute = AdminPostsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsSlugRoute,
} as any)
const AdminPostsSlugEditRoute = AdminPostsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPostsSlugRoute,
} as any)
const AdminProductsSlugIndexRoute = AdminProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsSlugRoute,
} as any)
const AdminProductsSlugEditRoute = AdminProductsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminProductsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/posts/$slug/': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug/': typeof AdminProductsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/posts/$slug': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug': typeof AdminProductsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/posts/$slug/': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug/': typeof AdminProductsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/admin/'
    | '/blog/'
    | '/catalogue/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/posts/$slug/'
    | '/admin/products/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/admin/posts/new'
    | '/admin/products/new'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/posts/$slug'
    | '/admin/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/admin/'
    | '/blog/'
    | '/catalogue/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/posts/$slug/'
    | '/admin/products/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CatalogueRoute: typeof CatalogueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$slug': {
      id: '/admin/posts/$slug'
      path: '/$slug'
      fullPath: '/admin/posts/$slug'
      preLoaderRoute: typeof AdminPostsSlugRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/posts/$slug/': {
      id: '/admin/posts/$slug/'
      path: '/'
      fullPath: '/admin/posts/$slug/'
      preLoaderRoute: typeof AdminPostsSlugIndexRouteImport
      parentRoute: typeof AdminPostsSlugRoute
    }
    '/admin/posts/$slug/edit': {
      id: '/admin/posts/$slug/edit'
      path: '/edit'
      fullPath: '/admin/posts/$slug/edit'
      preLoaderRoute: typeof AdminPostsSlugEditRouteImport
      parentRoute: typeof AdminPostsSlugRoute
    }
    '/admin/products/$slug/': {
      id: '/admin/products/$slug/'
      path: '/'
      fullPath: '/admin/products/$slug/'
      preLoaderRoute: typeof AdminProductsSlugIndexRouteImport
      parentRoute: typeof AdminProductsSlugRoute
    }
    '/admin/products/$slug/edit': {
      id: '/admin/products/$slug/edit'
      path: '/edit'
      fullPath: '/admin/products/$slug/edit'
      preLoaderRoute: typeof AdminProductsSlugEditRouteImport
      parentRoute: typeof AdminProductsSlugRoute
    }
  }
}

interface AdminPostsSlugRouteChildren {
  AdminPostsSlugEditRoute: typeof AdminPostsSlugEditRoute
  AdminPostsSlugIndexRoute: typeof AdminPostsSlugIndexRoute
}

const AdminPostsSlugRouteChildren: AdminPostsSlugRouteChildren = {
  AdminPostsSlugEditRoute: AdminPostsSlugEditRoute,
  AdminPostsSlugIndexRoute: AdminPostsSlugIndexRoute,
}

const AdminPostsSlugRouteWithChildren = AdminPostsSlugRoute._addFileChildren(
  AdminPostsSlugRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsSlugRoute: typeof AdminPostsSlugRouteWithChildren
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsSlugRoute: AdminPostsSlugRouteWithChildren,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminProductsSlugRouteChildren {
  AdminProductsSlugEditRoute: typeof AdminProductsSlugEditRoute
  AdminProductsSlugIndexRoute: typeof AdminProductsSlugIndexRoute
}

const AdminProductsSlugRouteChildren: AdminProductsSlugRouteChildren = {
  AdminProductsSlugEditRoute: AdminProductsSlugEditRoute,
  AdminProductsSlugIndexRoute: AdminProductsSlugIndexRoute,
}

const AdminProductsSlugRouteWithChildren =
  AdminProductsSlugRoute._addFileChildren(AdminProductsSlugRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRouteWithChildren
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRouteWithChildren,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CatalogueRouteChildren {
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CatalogueRoute: CatalogueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
