/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPrivacyRouteImport } from './routes/admin.privacy'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthGithubRouteImport } from './routes/auth.github'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysSlugRouteImport } from './routes/stays.$slug'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsSlugRouteImport } from './routes/admin.posts.$slug'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsSlugRouteImport } from './routes/admin.products.$slug'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin.properties.index'
import { Route as AdminPropertiesSlugRouteImport } from './routes/admin.properties.$slug'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin.properties.new'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as AdminServicesSlugRouteImport } from './routes/admin.services.$slug'
import { Route as AdminServicesNewRouteImport } from './routes/admin.services.new'
import { Route as AdminPostsSlugIndexRouteImport } from './routes/admin.posts.$slug.index'
import { Route as AdminPostsSlugEditRouteImport } from './routes/admin.posts.$slug.edit'
import { Route as AdminProductsSlugIndexRouteImport } from './routes/admin.products.$slug.index'
import { Route as AdminProductsSlugEditRouteImport } from './routes/admin.products.$slug.edit'
import { Route as AdminProductsSlugSaleRouteImport } from './routes/admin.products.$slug.sale'
import { Route as AdminPropertiesSlugIndexRouteImport } from './routes/admin.properties.$slug.index'
import { Route as AdminPropertiesSlugEditRouteImport } from './routes/admin.properties.$slug.edit'
import { Route as AdminServicesSlugIndexRouteImport } from './routes/admin.services.$slug.index'
import { Route as AdminServicesSlugEditRouteImport } from './routes/admin.services.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrivacyRoute = AdminPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogueRoute,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogueRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaysRoute,
} as any)
const StaysSlugRoute = StaysSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StaysRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsSlugRoute = AdminPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPropertiesRoute,
} as any)
const AdminPropertiesSlugRoute = AdminPropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminPropertiesRoute,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPropertiesRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminServicesSlugRoute = AdminServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminPostsSlugIndexRoute = AdminPostsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsSlugRoute,
} as any)
const AdminPostsSlugEditRoute = AdminPostsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPostsSlugRoute,
} as any)
const AdminProductsSlugIndexRoute = AdminProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsSlugRoute,
} as any)
const AdminProductsSlugEditRoute = AdminProductsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminProductsSlugRoute,
} as any)
const AdminProductsSlugSaleRoute = AdminProductsSlugSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AdminProductsSlugRoute,
} as any)
const AdminPropertiesSlugIndexRoute =
  AdminPropertiesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPropertiesSlugRoute,
  } as any)
const AdminPropertiesSlugEditRoute = AdminPropertiesSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPropertiesSlugRoute,
} as any)
const AdminServicesSlugIndexRoute = AdminServicesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServicesSlugRoute,
} as any)
const AdminServicesSlugEditRoute = AdminServicesSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminServicesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/stays': typeof StaysRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/properties': typeof AdminPropertiesRouteWithChildren
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/github': typeof AuthGithubRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/stays/': typeof StaysIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/properties/$slug': typeof AdminPropertiesSlugRouteWithChildren
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/admin/services/$slug': typeof AdminServicesSlugRouteWithChildren
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/products/$slug/sale': typeof AdminProductsSlugSaleRoute
  '/admin/properties/$slug/edit': typeof AdminPropertiesSlugEditRoute
  '/admin/services/$slug/edit': typeof AdminServicesSlugEditRoute
  '/admin/posts/$slug/': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug/': typeof AdminProductsSlugIndexRoute
  '/admin/properties/$slug/': typeof AdminPropertiesSlugIndexRoute
  '/admin/services/$slug/': typeof AdminServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/github': typeof AuthGithubRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/stays': typeof StaysIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/products/$slug/sale': typeof AdminProductsSlugSaleRoute
  '/admin/properties/$slug/edit': typeof AdminPropertiesSlugEditRoute
  '/admin/services/$slug/edit': typeof AdminServicesSlugEditRoute
  '/admin/posts/$slug': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug': typeof AdminProductsSlugIndexRoute
  '/admin/properties/$slug': typeof AdminPropertiesSlugIndexRoute
  '/admin/services/$slug': typeof AdminServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/stays': typeof StaysRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/properties': typeof AdminPropertiesRouteWithChildren
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/github': typeof AuthGithubRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/cart': typeof ShopCartRoute
  '/stays/$slug': typeof StaysSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/stays/': typeof StaysIndexRoute
  '/admin/posts/$slug': typeof AdminPostsSlugRouteWithChildren
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/$slug': typeof AdminProductsSlugRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/properties/$slug': typeof AdminPropertiesSlugRouteWithChildren
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/admin/services/$slug': typeof AdminServicesSlugRouteWithChildren
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
  '/admin/products/$slug/edit': typeof AdminProductsSlugEditRoute
  '/admin/products/$slug/sale': typeof AdminProductsSlugSaleRoute
  '/admin/properties/$slug/edit': typeof AdminPropertiesSlugEditRoute
  '/admin/services/$slug/edit': typeof AdminServicesSlugEditRoute
  '/admin/posts/$slug/': typeof AdminPostsSlugIndexRoute
  '/admin/products/$slug/': typeof AdminProductsSlugIndexRoute
  '/admin/properties/$slug/': typeof AdminPropertiesSlugIndexRoute
  '/admin/services/$slug/': typeof AdminServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/login'
    | '/privacy'
    | '/services'
    | '/shop'
    | '/stays'
    | '/admin/access'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/privacy'
    | '/admin/products'
    | '/admin/properties'
    | '/admin/reservations'
    | '/admin/services'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/github'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/services/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/stays/$slug'
    | '/admin/'
    | '/blog/'
    | '/catalogue/'
    | '/services/'
    | '/shop/'
    | '/stays/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/properties/$slug'
    | '/admin/properties/new'
    | '/admin/services/$slug'
    | '/admin/services/new'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/properties/'
    | '/admin/services/'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/products/$slug/sale'
    | '/admin/properties/$slug/edit'
    | '/admin/services/$slug/edit'
    | '/admin/posts/$slug/'
    | '/admin/products/$slug/'
    | '/admin/properties/$slug/'
    | '/admin/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/privacy'
    | '/admin/access'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/orders'
    | '/admin/privacy'
    | '/admin/reservations'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/github'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/services/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/stays/$slug'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/services'
    | '/shop'
    | '/stays'
    | '/admin/posts/new'
    | '/admin/products/new'
    | '/admin/properties/new'
    | '/admin/services/new'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/properties'
    | '/admin/services'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/products/$slug/sale'
    | '/admin/properties/$slug/edit'
    | '/admin/services/$slug/edit'
    | '/admin/posts/$slug'
    | '/admin/products/$slug'
    | '/admin/properties/$slug'
    | '/admin/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/blog'
    | '/catalogue'
    | '/login'
    | '/privacy'
    | '/services'
    | '/shop'
    | '/stays'
    | '/admin/access'
    | '/admin/bookings'
    | '/admin/enquiries'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/privacy'
    | '/admin/products'
    | '/admin/properties'
    | '/admin/reservations'
    | '/admin/services'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/github'
    | '/blog/$slug'
    | '/catalogue/$slug'
    | '/services/$slug'
    | '/shop/$slug'
    | '/shop/cart'
    | '/stays/$slug'
    | '/admin/'
    | '/blog/'
    | '/catalogue/'
    | '/services/'
    | '/shop/'
    | '/stays/'
    | '/admin/posts/$slug'
    | '/admin/posts/new'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/properties/$slug'
    | '/admin/properties/new'
    | '/admin/services/$slug'
    | '/admin/services/new'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/properties/'
    | '/admin/services/'
    | '/admin/posts/$slug/edit'
    | '/admin/products/$slug/edit'
    | '/admin/products/$slug/sale'
    | '/admin/properties/$slug/edit'
    | '/admin/services/$slug/edit'
    | '/admin/posts/$slug/'
    | '/admin/products/$slug/'
    | '/admin/properties/$slug/'
    | '/admin/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CatalogueRoute: typeof CatalogueRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  StaysRoute: typeof StaysRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGithubRoute: typeof AuthGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/privacy': {
      id: '/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AdminPrivacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/stays/': {
      id: '/stays/'
      path: '/'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/$slug': {
      id: '/stays/$slug'
      path: '/$slug'
      fullPath: '/stays/$slug'
      preLoaderRoute: typeof StaysSlugRouteImport
      parentRoute: typeof StaysRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$slug': {
      id: '/admin/posts/$slug'
      path: '/$slug'
      fullPath: '/admin/posts/$slug'
      preLoaderRoute: typeof AdminPostsSlugRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminPropertiesRoute
    }
    '/admin/properties/$slug': {
      id: '/admin/properties/$slug'
      path: '/$slug'
      fullPath: '/admin/properties/$slug'
      preLoaderRoute: typeof AdminPropertiesSlugRouteImport
      parentRoute: typeof AdminPropertiesRoute
    }
    '/admin/properties/new': {
      id: '/admin/properties/new'
      path: '/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof AdminPropertiesRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/services/$slug': {
      id: '/admin/services/$slug'
      path: '/$slug'
      fullPath: '/admin/services/$slug'
      preLoaderRoute: typeof AdminServicesSlugRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/posts/$slug/': {
      id: '/admin/posts/$slug/'
      path: '/'
      fullPath: '/admin/posts/$slug/'
      preLoaderRoute: typeof AdminPostsSlugIndexRouteImport
      parentRoute: typeof AdminPostsSlugRoute
    }
    '/admin/posts/$slug/edit': {
      id: '/admin/posts/$slug/edit'
      path: '/edit'
      fullPath: '/admin/posts/$slug/edit'
      preLoaderRoute: typeof AdminPostsSlugEditRouteImport
      parentRoute: typeof AdminPostsSlugRoute
    }
    '/admin/products/$slug/': {
      id: '/admin/products/$slug/'
      path: '/'
      fullPath: '/admin/products/$slug/'
      preLoaderRoute: typeof AdminProductsSlugIndexRouteImport
      parentRoute: typeof AdminProductsSlugRoute
    }
    '/admin/products/$slug/edit': {
      id: '/admin/products/$slug/edit'
      path: '/edit'
      fullPath: '/admin/products/$slug/edit'
      preLoaderRoute: typeof AdminProductsSlugEditRouteImport
      parentRoute: typeof AdminProductsSlugRoute
    }
    '/admin/products/$slug/sale': {
      id: '/admin/products/$slug/sale'
      path: '/sale'
      fullPath: '/admin/products/$slug/sale'
      preLoaderRoute: typeof AdminProductsSlugSaleRouteImport
      parentRoute: typeof AdminProductsSlugRoute
    }
    '/admin/properties/$slug/': {
      id: '/admin/properties/$slug/'
      path: '/'
      fullPath: '/admin/properties/$slug/'
      preLoaderRoute: typeof AdminPropertiesSlugIndexRouteImport
      parentRoute: typeof AdminPropertiesSlugRoute
    }
    '/admin/properties/$slug/edit': {
      id: '/admin/properties/$slug/edit'
      path: '/edit'
      fullPath: '/admin/properties/$slug/edit'
      preLoaderRoute: typeof AdminPropertiesSlugEditRouteImport
      parentRoute: typeof AdminPropertiesSlugRoute
    }
    '/admin/services/$slug/': {
      id: '/admin/services/$slug/'
      path: '/'
      fullPath: '/admin/services/$slug/'
      preLoaderRoute: typeof AdminServicesSlugIndexRouteImport
      parentRoute: typeof AdminServicesSlugRoute
    }
    '/admin/services/$slug/edit': {
      id: '/admin/services/$slug/edit'
      path: '/edit'
      fullPath: '/admin/services/$slug/edit'
      preLoaderRoute: typeof AdminServicesSlugEditRouteImport
      parentRoute: typeof AdminServicesSlugRoute
    }
  }
}

interface AdminPostsSlugRouteChildren {
  AdminPostsSlugEditRoute: typeof AdminPostsSlugEditRoute
  AdminPostsSlugIndexRoute: typeof AdminPostsSlugIndexRoute
}

const AdminPostsSlugRouteChildren: AdminPostsSlugRouteChildren = {
  AdminPostsSlugEditRoute: AdminPostsSlugEditRoute,
  AdminPostsSlugIndexRoute: AdminPostsSlugIndexRoute,
}

const AdminPostsSlugRouteWithChildren = AdminPostsSlugRoute._addFileChildren(
  AdminPostsSlugRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsSlugRoute: typeof AdminPostsSlugRouteWithChildren
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsSlugRoute: AdminPostsSlugRouteWithChildren,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminProductsSlugRouteChildren {
  AdminProductsSlugEditRoute: typeof AdminProductsSlugEditRoute
  AdminProductsSlugSaleRoute: typeof AdminProductsSlugSaleRoute
  AdminProductsSlugIndexRoute: typeof AdminProductsSlugIndexRoute
}

const AdminProductsSlugRouteChildren: AdminProductsSlugRouteChildren = {
  AdminProductsSlugEditRoute: AdminProductsSlugEditRoute,
  AdminProductsSlugSaleRoute: AdminProductsSlugSaleRoute,
  AdminProductsSlugIndexRoute: AdminProductsSlugIndexRoute,
}

const AdminProductsSlugRouteWithChildren =
  AdminProductsSlugRoute._addFileChildren(AdminProductsSlugRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRouteWithChildren
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRouteWithChildren,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminPropertiesSlugRouteChildren {
  AdminPropertiesSlugEditRoute: typeof AdminPropertiesSlugEditRoute
  AdminPropertiesSlugIndexRoute: typeof AdminPropertiesSlugIndexRoute
}

const AdminPropertiesSlugRouteChildren: AdminPropertiesSlugRouteChildren = {
  AdminPropertiesSlugEditRoute: AdminPropertiesSlugEditRoute,
  AdminPropertiesSlugIndexRoute: AdminPropertiesSlugIndexRoute,
}

const AdminPropertiesSlugRouteWithChildren =
  AdminPropertiesSlugRoute._addFileChildren(AdminPropertiesSlugRouteChildren)

interface AdminPropertiesRouteChildren {
  AdminPropertiesSlugRoute: typeof AdminPropertiesSlugRouteWithChildren
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
}

const AdminPropertiesRouteChildren: AdminPropertiesRouteChildren = {
  AdminPropertiesSlugRoute: AdminPropertiesSlugRouteWithChildren,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
}

const AdminPropertiesRouteWithChildren = AdminPropertiesRoute._addFileChildren(
  AdminPropertiesRouteChildren,
)

interface AdminServicesSlugRouteChildren {
  AdminServicesSlugEditRoute: typeof AdminServicesSlugEditRoute
  AdminServicesSlugIndexRoute: typeof AdminServicesSlugIndexRoute
}

const AdminServicesSlugRouteChildren: AdminServicesSlugRouteChildren = {
  AdminServicesSlugEditRoute: AdminServicesSlugEditRoute,
  AdminServicesSlugIndexRoute: AdminServicesSlugIndexRoute,
}

const AdminServicesSlugRouteWithChildren =
  AdminServicesSlugRoute._addFileChildren(AdminServicesSlugRouteChildren)

interface AdminServicesRouteChildren {
  AdminServicesSlugRoute: typeof AdminServicesSlugRouteWithChildren
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesSlugRoute: AdminServicesSlugRouteWithChildren,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminPrivacyRoute: typeof AdminPrivacyRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPropertiesRoute: typeof AdminPropertiesRouteWithChildren
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminPrivacyRoute: AdminPrivacyRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPropertiesRoute: AdminPropertiesRouteWithChildren,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CatalogueRouteChildren {
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCartRoute: ShopCartRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface StaysRouteChildren {
  StaysSlugRoute: typeof StaysSlugRoute
  StaysIndexRoute: typeof StaysIndexRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysSlugRoute: StaysSlugRoute,
  StaysIndexRoute: StaysIndexRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CatalogueRoute: CatalogueRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  StaysRoute: StaysRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGithubRoute: AuthGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
